Description: 
  Manuel Castellin <manuel@castellinconsulting.com> Udacity DevOps Capstone Project
  An infrastructure to deploy a Kubernetes cluster with one Master node and two Minions in AWS

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String
  
  KeyPairName:
    Description: The KeyPair name to use for ssh access to instances
    Type: String

Resources:

  EC2AdmSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to EC2 instances for administrative purposes
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  K8sMasterControlInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: A network interface for administraction traffic to k8s instances
      SubnetId: 
        Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
      GroupSet:
        - Ref: EC2AdmSecGroup

  K8sMasterInstance:
    Type: AWS::EC2::Instance
    Description: An EC2 instance to hold the Kubernetes master node
    Properties:
#     UserData:
#       Fn::Base64: !Sub |
#         #!/bin/bash
#         echo "Applying updates..."
#         echo "Done."
      ImageId: ami-0b418580298265d5c
      KeyName: !Ref KeyPairName
      InstanceType: t3.small
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: '10'
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref K8sMasterControlInterface
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-k8s-master"



