---

apiVersion: v1
kind: Service
metadata:
  name: capstone-api-svc
spec:
  selector:
    app: capstone-api
    release: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: green-capstone-api-svc
spec:
  selector:
    app: capstone-api
    release: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: blue-capstone-api-svc
spec:
  selector:
    app: capstone-api
    release: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: capstone-api-is
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: capstone-api-svc
          servicePort: 80
      - path: /green/api
        backend:
          serviceName: green-capstone-api-svc
          servicePort: 80
      - path: /blue/api
        backend:
          serviceName: blue-capstone-api-svc
          servicePort: 80

