---

- name: Install package
  hosts: all
  tasks:

    - name: add RPM key for Jenkins
      become: yes
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: include Jenkins repo
      become: yes
      yum_repository:
        name: jenkins
        description: the official jenkins repo
        baseurl: https://pkg.jenkins.io/redhat-stable/

    - name: install required packages
      become: yes
      yum:
        name:
          - git
          - java-1.8.0-openjdk
          - jenkins
        state: present

#   - name: install Jenkins plugins
#     jenkins_plugin:
#       name: blueocean
#       state: latest

    - name: enable Jenkins service
      become: yes
      service:
        name: jenkins
        enabled: yes
        state: started
